name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  powersync: ^1.4.2

dev_dependencies:
  logger: ^2.3.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
